# -*- coding: utf-8 -*-
"""duplicate_remover.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ttmryQNS_YZ139UZxXJQSPkspHvR-cS
"""

# This script removes duplicate (100% overlap) sequences in your fasta files
import os
from Bio import SeqIO

seen = []
records = []

for record in SeqIO.parse("ALL_PICIS", "fasta"):  
    if str(record.seq) not in seen:
        seen.append(str(record.seq))
        records.append(record)

SeqIO.write(records, "ALL_PICIS_duplicates_removed", "fasta")